main: eu.r5t.mclogin.Main
name: mc-login
version: 2023-02-13
api-version: 1.19

commands:
  ip:
    usage: /ip
  reload-login:
    usage: /reload-login
  whitelist:
    usage: /whitelist [reload|clear|list] [add|remove <ip>]
  fails:
    usage: /fails [reload|clear|list] [add|remove <ip>]
